
# This a sample workflow to run 3 jobs pointing to 3 different servers.

name: Sample Manual Workflow to run jobs on Three Environments

# Controls when the action will run
on:
  # Lets you trigger the workflow manually
  workflow_dispatch:

# A workflow run has one or more jobs that can run seqentially or parallel
jobs:
  # 1st Job Name: DEV
  DEV:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: DEV
    # Steps that are executed sequentially
    steps:
    # Step 1
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    # Step 2
    - name: Run a script
      run: |
        echo "1st job ran successfully on ${{secrets.ENV_NAME}} environment"


  # 2nd Job Name: QA
  QA:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: QA
    needs: DEV # Requires DEV job to complete successfully 
    steps:
    # Step 1
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    # Step 2
    - name: Run a script
      run: |
        echo "2nd job ran successfully on ${{secrets.ENV_NAME}} environment"

  # 3rd Job Name: PROD
  PROD:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: PROD
    steps:
    # Step 1
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # Step 2
    - name: Run a script
      run: |
        echo "1st job ran successfully on ${{secrets.ENV_NAME}} environment"

